services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - app-network  # Ensure the PHP container is on the same network

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fws-db-dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./probafeladat.dump.sql:/docker-entrypoint-initdb.d/probafeladat.dump.sql
    networks:
      - app-network  # Ensure the MySQL container is on the same network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge  # Define a custom network for communication between containers
